#cloud-config
users:
  - name: rke2-user
    groups: users, admin
    sudo: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
      %{ if length(public_key) > 0 }
    ssh_authorized_keys:
      %{ for ssh_key in public_key }
      - ssh-rsa ${ssh_key}
        %{ endfor }
        %{ endif }
write_files:
  - path: /etc/rancher/rke2/config.yaml
    permissions: "0600"
    owner: root:root
    content: |
      server: https://${lb_address}:9345
      token: ${rke2_cluster_secret}
      cloud-provider-name: external
      kube-apiserver-arg:
        - kubelet-preferred-address-types=InternalIP
  - path: /opt/rke2/run_rke2.sh
    permissions: "0755"
    owner: root:root
    content: |
      #!/bin/bash
      curl -fsSL https://raw.githubusercontent.com/rancher/rke2/master/install.sh --output /root/install.sh
      chmod u+x /root/install.sh
      INSTALL_RKE2_METHOD='tar' INSTALL_RKE2_TYPE=agent INSTALL_RKE2_VERSION=${rke2_version} /root/install.sh
      systemctl enable rke2-agent
      systemctl start rke2-agent
      sleep 20
      for bin in $(readlink -f /var/lib/rancher/rke2/bin/*); do
        ln -sf $bin /usr/local/bin/$(basename $bin)
      done
runcmd:
  - apt-get update
  - apt-get install -y git vim software-properties-common resolvconf linux-headers-$(uname -r) jq curl open-iscsi
  - max_retries=30; retries=0; while [ ! -f '/etc/rancher/rke2/rke2.yaml' ] && [ $retries -lt $max_retries ]; do   echo 'File not found. Retrying in 5 seconds...' &&  retries=$((retries+1)) && sleep 5; done; /opt/rke2/run_rke2.sh
  - rm -f /opt/rke2/run_rke2.sh
  - echo "nameserver 1.1.1.1" > /etc/resolvconf/resolv.conf.d/tail
  - echo "RateLimitIntervalSec=0" >> /etc/systemd/journald.conf
  - echo "RateLimitBurst=0" >> /etc/systemd/journald.conf
  - systemctl restart systemd-journald.service
  - systemctl start resolvconf
  - cat /root/.ssh/authorized_keys >  /home/rke2-user/.ssh/authorized_keys
  - chown -R rke2-user:rke2-user  /home/rke2-user/.ssh
  - chmod 700 /home/rke2-user/.ssh
  - chmod 600 /home/rke2-user/.ssh/authorized_keys
  - cat /etc/rancher/rke2/rke2.yaml > /root/.kube/config
  - chmod 600 /root/.kube/config
  - sed -ie '/#Port 22/s/^.*$/Port 2233/' /etc/ssh/sshd_config
  - sed -ie '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -ie '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -ie '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -ie '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers rke2-user' /etc/ssh/sshd_config
  - systemctl restart ssh

